---

services:

  matrix:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    environment:
      - TS_HOSTNAME=matrix
      - TS_SERVE_PORT=${MATRIX_INTERNAL_PORT?error}
    tmpfs:
      - /tmp
    networks:
      - matrix
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
