---

# OFFICIAL: https://tailscale.dev/blog/docker-mod-tailscale
# UNofficial: docker + tailscale: https://mrpowergamerbr.com/us/blog/2023-03-20-untangling-your-network-tailscale-in-docker-compose/

#@TODO  https://mszpro.com/blog/matrix-sliding-sync/


services:

  matrix:
    image: matrixdotorg/synapse:latest
    # hostname: homeserver
    environment:
      - SYNAPSE_SERVER_NAME=${MATRIX_SERVER_NAME?error}
      - SYNAPSE_REPORT_STATS=no
    configs:
      # - source: homeserver.yml
        # target: /data/homeserver.yaml
      - source: synapse-init.sh
        mode: 0555
    volumes:
      - ${MATRIX_APP_DATA?error}/data:/data
    network_mode: service:matrix-ts
    entrypoint: /synapse-init.sh

  hb:
    image: hif1/heisenbridge:latest
    hostname: heisenbridge
    volumes:
      - ${MATRIX_APP_DATA?error}/data:/data
    configs:
      # - heisenbridge.yml
      - source: heisenbridge-init.sh
        mode: 0555
    networks:
      - heisenbridge
    # command: --config /heisenbridge.yml --listen-address 0.0.0.0 http://matrix:${MATRIX_INTERNAL_PORT?error}
    entrypoint: /heisenbridge-init.sh


  sliding-sync:
    image: ghcr.io/matrix-org/sliding-sync:latest
    environment:
      SYNCV3_SERVER: http://matrix:${MATRIX_INTERNAL_PORT?error}
      SYNCV3_SECRET: ${SLIDING_SYNC_SECRET?error}
      SYNCV3_BINDADDR: :${SLIDING_SYNC_INTERNAL_PORT?error}
      SYNCV3_DB: "postgres://${POSTGRES_USER?error}:${POSTGRES_PASSWORD?error}@postgres:${POSTGRES_PORT?error}/syncv3?sslmode=disable"
    depends_on:
      - postgres
    networks:
      # - matrix
      - sliding-sync

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: syncv3
      POSTGRES_USER: ${POSTGRES_USER?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?error}
    networks:
      # - matrix
      - sliding-sync
    volumes:
      - postgres-data:/var/lib/postgresql/data
#
#
#   discord:
#     image: dock.mau.dev/mautrix/discord
#     restart: unless-stopped
#     volumes:
#       - ${DISCORD_BRIDGE_APP_DATA?error}/data:/data
#     networks:
#       - discord

    # If you put the service above in the same docker-compose as the homeserver,
    # ignore the parts below. Otherwise, see below for configuring networking.

    # If synapse is running outside of docker, you'll need to expose the port.
    # Note that in most cases you should either run everything inside docker
    # or everything outside docker, rather than mixing docker things with
    # non-docker things.
    #ports:
    #- "29334:29334"
    # You'll also probably want this so the bridge can reach Synapse directly
    # using something like `http://host.docker.internal:8008` as the address:
    #extra_hosts:
    #- "host.docker.internal:host-gateway"

    # If synapse is in a different network, then add this container to that network.
    #networks:
    #- synapsenet
# This is also a part of the networks thing above
#networks:
#  synapsenet:
#    external:
#      name: synapsenet