---

# @TODO review these https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
# @TODO https://github.com/TheUltimateC0der/Listrr
# @TODO https://blog.gitguardian.com/how-to-improve-your-docker-containers-security-cheat-sheet/


name: media #@TODO remove and recreate all services

include:

  - path: ./secrets.yml

  - path: ./tailscale.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

  - path: ./services.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

  - path: ./configs.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

volumes:
  bazarr-ts:
  calibre-ts:
  calibre-web-ts:
  gluetun:
  lidarr-ts:
  nzbget-main:
  nzbget-ts:
  overseerr-ts:
  plex-ts:
  prowlarr-ts:
  qbittorrent-ts:
  radarr-ts:
  readarr-ts:
  slippi-transmission-ts:
  sonarr-ts:

networks:
  bazarr-ts:
  bazarr:
  calibre-ts:
  calibre-web-ts:
  calibre-web:
  calibre:
  gluetun:
  lidarr-ts:
  lidarr:
  nzbget:
  overseerr-ts:
  overseerr:
  plex-ts:
  plex:
  prowlarr-ts:
  prowlarr:
  qbittorrent-ts:
  qbittorrent:
  radarr-ts:
  readarr-ts:
  readarr:
  recyclarr:
    internal: true
  sonarr-ts:
  sonarr:
  unpackerr:
    internal: true
  nzbget-ts:
  slippi-transmission-ts:
  radarr:
