---

# @TODO review these https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
# @TODO https://github.com/TheUltimateC0der/Listrr


include:
  - path: ./compose.rss-apps.yml
    env_file:
      - ./.envrc
      - ./.secrets


networks:
  miniflux:
