configs:
  miniflux-ts:
    content: |
      {
        "TCP": {
          "443": {
            "HTTPS": true
          }
        },
        "Web": {
          "$${TS_CERT_DOMAIN}:443": {
            "Handlers": {
              "/": {
                "Proxy": "http://miniflux:${MINIFLUX_PORT?error}"
              }
            }
          }
        }
      }

  rsshub-ts:
    content: |
      {
        "TCP": {
          "443": {
            "HTTPS": true
          }
        },
        "Web": {
          "$${TS_CERT_DOMAIN}:443": {
            "Handlers": {
              "/": {
                "Proxy": "http://rsshub:${RSSHUB_PORT?error}"
              }
            }
          }
        }
      }
