services:




  defaults:
    extends:
      file: __base.yml
      service: __base
    tmpfs:
      - /tmp
      - /run
      - /var/run
    environment:
      - TZ=${TZ?error}
      - PGID=${PGID?error}
      - PUID=${PUID?error}

  lsio:
    # image: lscr.io/linuxserver/____:latest
    extends:
      file: __base.yml
      service: __base
    tmpfs:
      - /run:exec
      - /tmp
    environment:
      - TZ=${TZ?error}
      - PGID=${PGID?error}
      - PUID=${PUID?error}
    cap_add:
      - CHOWN
      - SETGID
      - SETUID



  tailscale:
    extends:
      file: __base.yml
      service: __base
    image: tailscale/tailscale
    read_only: false # this needs resolved first https://github.com/docker/compose/issues/12031
    environment:
      - TZ=${TZ?error}
      - TS_ACCEPT_DNS=true
      - TS_AUTHKEY=${TS_AUTHKEY?error}
      - TS_STATE_DIR=${TS_STATE_DIR?error}
      - TS_USERSPACE=true
    volumes:
      - ${TS_STATE_DIR?error}
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60
    dns: 100.100.100.100


  mariadb:
    extends:
      file: __base.yml
      service: __base
    image: mariadb
    tmpfs:
      - /tmp
      - /run/mysqld
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s
    expose:
      - 3306
    cap_add:
     - SETGID
     - SETUID
     - CHOWN
     - DAC_OVERRIDE
    environment:
      - TZ=${TZ?error}
      - PGID=${PGID?error}
      - PUID=${PUID?error}

  redis:
    extends:
      file: __base.yml
      service: __base
    image: redis:alpine
    restart: always
    read_only: true
    cap_drop: [ALL]
    cap_add:
      - SETGID
      - SETUID
    environment:
      - PGID=${PGID?error}
      - PUID=${PUID?error}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
