---

services:


  dsm-ts:
    image: ghcr.io/josh1703658784/tailscale-serve-https:v1.72.1
    network_mode: host
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - LOCAL_PORT=${DSM_EXTERNAL_PORT}
      - TS_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TS_HOSTNAME=dsm
      - TS_USERSPACE=true
      - TS_ACCEPT_DNS=true
    volumes:
      - ${TAILSCALE_STATE_DIR?error}
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped



  # simple file server
  fileserver-ts:
    image: tailscale/tailscale:latest
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_SERVE_CONFIG=/config/fileserver.json
      - TS_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TS_HOSTNAME=fileserver
      - TS_USERSPACE=true
      - TS_ACCEPT_DNS=true
    volumes:
      - fileserver-ts:${TAILSCALE_STATE_DIR?error}
      - ${TAILSCALE_SERVE_CONFIGS}:/config:ro
      - /volume1/downloaded-media/data/media/movies:/downloads/movies:ro
      - /volume1/downloaded-media/data/media/books:/downloads/books:ro
      - /volume1/downloaded-media/data/media/tv:/downloads/tv:ro
      - /volume1/downloaded-media-slippi/transmission-downloads/complete:/downloads/slippi/music/downlods:ro
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60
    cap_add:
      - net_admin
      - sys_module
    networks:
      - fileserver-ts
    restart: unless-stopped


