---

services:

  fake-data-generator:
    image: ghcr.io/josh1703658784/fake-address-generator-docker:feature-hardcode-selected-states
    volumes:
      - tailscale-fake-data-generator:/var/lib/tailscale
    environment:
      - TAILSCALE_HOSTNAME=fake-data-generator
      - TAILSCALE_SERVE_PORT=${FAKE_DATA_GENERATOR_PORT?error}
      - DOCKER_MODS=${TAILSCALE_DOCKER_MOD?error}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY?error}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH?error}
      - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR?error}
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE?error}
    networks:
      - fake-data-generator
    restart: unless-stopped

