---

services:

  fake-data-generator-svc:
    image: ghcr.io/josh1703658784/fake-address-generator-docker:feature-hardcode-selected-states
    network_mode: service:fake-data-generator
    restart: unless-stopped



  portainer-svc:
    image: portainer/portainer-ce:2.21.1
    restart: unless-stopped
    network_mode: service:portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PORTAINER_APP_DATA?error}/data:/data
