---

services:

  fake-data-generator:
    image: ghcr.io/josh1703658784/fake-address-generator-docker:feature-hardcode-selected-states
    volumes:
      - tailscale-fake-data-generator:/var/lib/tailscale
    environment:
      - TAILSCALE_HOSTNAME=fake-data-generator
      - TAILSCALE_SERVE_PORT=${FAKE_DATA_GENERATOR_PORT?error}
      - DOCKER_MODS=${TAILSCALE_DOCKER_MOD?error}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY?error}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH?error}
      - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR?error}
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE?error}
    networks:
      - fake-data-generator
    restart: unless-stopped

  # fresh-rss:
  #   image: lscr.io/linuxserver/freshrss:latest
  #   environment:
  #     - PUID=${PUID?error}
  #     - PGID=${PGID?error}
  #     - TZ=${TZ?error}
  #     - TAILSCALE_HOSTNAME=rss
  #     - TAILSCALE_SERVE_PORT=${FRESH_RSS_INTERNAL_PORT?error}
  #     - DOCKER_MODS=${TAILSCALE_DOCKER_MOD?error}
  #     - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY?error}
  #     - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH?error}
  #     - TAILSCALE_STATE_DIR=${TAILSCALE_STATE_DIR?error}
  #     - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE?error}
  #   volumes:
  #     - ${FRESH_RSS_APP_DATA?error}/config:/config
  #     - tailscale-fresh-rss:/var/lib-tailscale
  #   networks:
  #     - fresh-rss
  #   restart: unless-stopped


  # minio:
  #   # image: bitnami/minio
  #   image: quay.io/minio/minio
  #   networks:
  #     - minio
  #   environment:
  #     - MINIO_ROOT_USER=${MINIO_ROOT_USER?error}
  #     - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD?error}
  #   volumes:
  #     - ${MINIO_BACKUP_DATA?error}:/data
  #   expose:
  #     - 9000 # api
  #     - 9001 # webui
  #   cap_add:
  #     - CHOWN
  #     - SETGID
  #     - SETUID
  #     - MKNOD                                                           # create tun device if not mounted from host
  #     - NET_RAW                                                         # iptables v1.8.10 (legacy): can't initialize iptables table `filter'
  #     - NET_ADMIN                                                       # required to establish vpn tunnel
  #     - FSETID
  #     - FOWNER
  #   command: server /data --console-address ":9001"


  # minio-tailscale:
  #   image: tailscale/tailscale
  #   network_mode: service:minio
  #   environment:
  #     - TS_AUTH_KEY=${TAILSCALE_AUTHKEY?error}
  #     - TS_HOSTNAME=minio
  #     - TS_SERVE_CONFIG=/serve-config/serve-config.json
  #   volumes:
  #     - /volume1/docker-user-data/service-configs.sync/minio-tailscale-serve-config/serve-config/:/serve-config:ro
  #     - tailscale-minio:/var/lib/tailscale
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_RAW
  #   depends_on:
  #     minio:
  #       condition: service_started
  #       restart: true
