---

services:


  dsm:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    network_mode: host
    environment:
      - TS_HOSTNAME=dsm
      - TS_SERVE_PORT=${DSM_EXTERNAL_PORT?error}

  # mostly for Harbour.app while on the go
  portainer:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    networks:
      - portainer
    environment:
      - TS_HOSTNAME=portainer
      - TS_SERVE_PORT=${PORTAINER_PORT?error}

  fake-data-generator:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    networks:
      - fake-data-generator
    environment:
      - TS_HOSTNAME=fake-data-generator
      - TS_SERVE_PORT=${FAKE_DATA_GENERATOR_PORT?error}

  # simple file server
  fileserver:
    extends:
      file: ./../common/services.yml
      service: tailscale-fileserver
    environment:
      - TS_SERVE_CONFIG=/config/fileserver.json
      - TS_HOSTNAME=fileserver
    volumes:
      - ${TS_SERVE_CONFIGS?error}:/config:ro
      - /volume1/downloaded-media/data/media/movies:/downloads/movies:ro
      - /volume1/downloaded-media/data/media/books:/downloads/books:ro
      - /volume1/downloaded-media/data/media/tv:/downloads/tv:ro
      - /volume1/downloaded-media-slippi/transmission-downloads/complete:/downloads/slippi/music/downlods:ro
    networks:
      - fileserver

#
