---

# @TODO review these https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
# @TODO https://github.com/TheUltimateC0der/Listrr


include:
  - path: ./services.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

  - path: ./tailscale.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

  - path: ./configs.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets



volumes:
  fake-data-generator-ts:
  fileserver-ts:
  portainer-ts:
  dsm-ts:
  rclone:
  change-detection-datastore:
  change-detection-ts:
  srm-ts:
  adguard-ts:


networks:
  fake-data-generator:
  fileserver:
  portainer:
  socket-proxy:
    internal: true
  dsm:
  change-detection-ts:
  srm:
  adguard:
