---

services:

#   change-detection:
#     image: dgtlmoon/changedetection.io
#     restart: always
#     networks:
#       - change-detection-ts
#     volumes:
#       - change-detection-datastore:/datastore
#
  fake-data-generator:
    image: ghcr.io/josh1703658784/fake-address-generator-docker:feature-hardcode-selected-states
    networks:
      - fake-data-generator
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.21.1
    restart: unless-stopped
    networks:
      - portainer
      - socket-proxy
    depends_on:
      - socket-proxy
    volumes:
      - ${PORTAINER_APP_DATA?error}/data:/data

  # rsync:
  #   image: alpine
  #   restart: unless-stopped
  #   volumes:
  #     - /volume1/torrent-downloads/torrent-downloads:/volume1/torrent-downloads/torrent-downloads
  #     - /volume3/REFURB/rsync/data:/volume3/REFURB/rsync/data:ro
  #   # entrypoint: tail -f /dev/null
  #   entrypoint: sh -c 'apk add rsync && rsync --archive --hard-links --progress --human-readable --partial --acls --xattrs /volume3/REFURB/rsync/data/ /volume1/torrent-downloads/torrent-downloads && echo DONE && echo sleeping && sleep 900'
  #   # options to look at later
  #   # --delete (on final?)
  #   # --checksum (on final?)
  #   # --itemize-changes
  #   # --quiet # only errors remain

  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    environment:
      - ALLOW_START=1 #optional
      - ALLOW_STOP=0 #optional
      - ALLOW_RESTARTS=1 #optional
      - AUTH=0 #optional
      - BUILD=0 #optional
      - COMMIT=0 #optional
      - CONFIGS=0 #optional
      - CONTAINERS=1 #optional
      - DISABLE_IPV6=0 #optional
      - DISTRIBUTION=0 #optional
      - EVENTS=1 #optional, DEFAULT=1
      - EXEC=0 #optional
      - IMAGES=0 #optional
      - INFO=1 #optional
      - NETWORKS=0 #optional
      - NODES=0 #optional
      - PING=1 #optional, DEFAULT=1
      - POST=0 #optional
      - PLUGINS=0 #optional
      - SECRETS=0 #optional
      - SERVICES=0 #optional
      - SESSION=0 #optional
      - SWARM=0 #optional
      - SYSTEM=0 #optional
      - TASKS=0 #optional
      - VERSION=1 #optional, DEFAULT=1
      - VOLUMES=0 #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - socket-proxy
    read_only: true
    tmpfs:
      - /run


  adguard:
    restart: unless-stopped
    image: adguard/adguardhome
    # volumes:
    #   - /opt/adguardhome/work
    #   - /opt/adguardhome/conf
    # ports:
    #   - 53:53/tcp
    #   - 53:53/udp
    #   # - 67:67/udp
    #   # - 68:68/udp
    #   - 80:80/tcp
    #   - 443:443/tcp
    #   - 443:443/udp
    #   - 3000:3000/tcp
    #   - 853:853/tcp
    #   - 784:784/udp
    #   - 853:853/udp
    #   - 8853:8853/udp
    #   - 5443:5443/tcp
    #   - 5443:5443/udp
    networks: [adguard]
