---

name: chat

include:

  - path: ./secrets.yml

  - path: ./services.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

  - path: ./tailscale.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

  - path: ./configs.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

volumes:
  # postgres-data:
  conduit-db:
  conduit-ts:
  heisenbridge-appservice:

networks:
  # matrix:
  heisenbridge:
  conduit-ts:
