
configs:

  conduit-ts:
    content: |
      {
        "TCP": {
          "443": {
            "HTTPS": true
          }
        },
        "Web": {
          "$${TS_CERT_DOMAIN}:443": {
            "Handlers": {
              "/": {
                "Proxy": "http://conduit:${CONDUIT_PORT?error}"
              }
            }
          }
        }
      }
