---

services:

  hb:
    extends:
      file: ./../common/services.yml
      service: defaults
    image: hif1/heisenbridge:latest
    hostname: heisenbridge
    read_only: false
    configs:
      - source: heisenbridge.yaml
        mode: 0555
    networks:
      - heisenbridge
    entrypoint: python -m heisenbridge --config /heisenbridge.yaml --listen-address=0.0.0.0 --listen-port=9898 http://conduit:6167


  # conduit.RS
  conduit:
    extends:
      file: ./../common/services.yml
      service: defaults
    image: matrixconduit/matrix-conduit:latest
    networks:
      - conduit-ts
      - heisenbridge
    volumes:
        - conduit-db:/var/lib/matrix-conduit/
    environment:
        CONDUIT_SERVER_NAME: conduit.stonecat-shark.ts.net # EDIT THIS
        CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
        CONDUIT_DATABASE_BACKEND: rocksdb
        CONDUIT_PORT: ${CONDUIT_PORT?error}
        CONDUIT_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
        CONDUIT_ALLOW_REGISTRATION: 'true'
        CONDUIT_ALLOW_FEDERATION: 'true'
        CONDUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
        CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
        #CONDUIT_MAX_CONCURRENT_REQUESTS: 100
        CONDUIT_ADDRESS: 0.0.0.0
        CONDUIT_CONFIG: '' # Ignore this
