---
# @TODO review these https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
# @TODO https://github.com/TheUltimateC0der/Listrr

services:

  transmission:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    environment:
      - TS_HOSTNAME=slippi-transmission
      - TS_SERVE_PORT=${TRANSMISSION_INTERNAL_PORT?error}
    tmpfs:
      - /tmp
    networks:
      - transmission
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

