---

# interpolation regex
# https://docs.docker.com/compose/environment-variables/variable-interpolation/#interpolation-syntax
# find: \${([A-Z_]+)}
# replace: ${$1?error}

services:


  plex:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    environment:
      - TS_HOSTNAME=plex
      - TS_SERVE_PORT=${PLEX_PORT?error}
    networks:
      - plex


  radarr:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    environment:
      - TS_HOSTNAME=radarr
      - TS_SERVE_PORT=${RADARR_PORT?error}
    networks:
      - bazarr
      - doplarr
      - sabnzbd
      - prowlarr
      - overseerr
      - recyclarr
      - qbittorrent

  sonarr:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    environment:
      - TS_HOSTNAME=sonarr
      - TS_SERVE_PORT=${SONARR_PORT?error}
    networks:
      - bazarr
      - sabnzbd
      - doplarr
      - prowlarr
      - overseerr
      - recyclarr
      - qbittorrent


  lidarr:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    environment:
      - TS_HOSTNAME=lidarr
      - TS_SERVE_PORT=${LIDARR_PORT?error}
    networks:
      - sabnzbd
      - prowlarr
      - qbittorrent

  readarr:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    environment:
      - TS_HOSTNAME=readarr
      - TS_SERVE_PORT=${READARR_PORT?error}
    networks:
      - sabnzbd
      - qbittorrent
      - prowlarr

  prowlarr:
      extends:
        file: ./../common/services.yml
        service: tailscale-proxy
      environment:
        - TS_HOSTNAME=prowlarr
        - TS_SERVE_PORT=${PROWLARR_PORT?error}
      networks:
        - prowlarr

  bazarr:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    environment:
      - TS_HOSTNAME=bazarr
      - TS_SERVE_PORT=${BAZARR_PORT?error}
    networks:
      - bazarr



  qb:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    networks:
      - qbittorrent
    environment:
      - TS_HOSTNAME=qb
      - TS_SERVE_PORT=${QBITTORRENT_INTERNAL_PORT?error}
      - TS_ACCEPT_DNS=false


  sab:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    networks:
      - sabnzbd
    environment:
      - TS_HOSTNAME=sab
      - TS_SERVE_PORT=${SABNZBD_INTERNAL_PORT?error}
      - TS_ACCEPT_DNS=false


  overseerr:
    extends:
      file: ./../common/services.yml
      service: tailscale-proxy
    networks:
      - plex
      - overseerr
    environment:
      - TS_HOSTNAME=overseerr
      - TS_SERVE_PORT=${OVERSEERR_PORT?error}


