---

name: utilities

include:
  - path: ./services.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc

  - path: ./tailscale.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc

  - path: ./configs.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc

volumes:
  change-detection-datastore:
  change-detection-ts:
  dsm-ts:
  fake-data-generator-ts:
  portainer-ts:
  uptime-kuma-ts:
  uptime-kuma:

networks:
  autoheal:
    internal: true
  dsm:
  change-detection-ts:
  fake-data-generator-ts:
  portainer:
    internal: true
  portainer-ts:
  uptime-kuma:
  uptime-kuma-ts:
