---

services:

  change-detection:
    image: dgtlmoon/changedetection.io
    restart: always
    networks:
      - change-detection-ts # SELF-TS
    volumes:
      - change-detection-datastore:/datastore

  autoheal:
    extends:
      file: ./../common/services.yml
      service: defaults
    image: willfarrell/autoheal
    cap_add: [ALL]
    networks:
      - autoheal # SELF
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - DOCKER_SOCK=tcp://socket-proxy:2375
      - AUTOHEAL_INTERVAL=5

  fake-data-generator:
    image: ghcr.io/josh1703658784/fake-address-generator-docker:feature-hardcode-selected-states
    networks:
      - fake-data-generator-ts # SELF-TS
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.21.1
    restart: unless-stopped
    networks:
      - portainer-ts
      - portainer
    depends_on:
      - socket-proxy
    volumes:
      - ${PORTAINER_APP_DATA?error}/data:/data

  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    networks:
      - uptime-kuma # SELF
      - uptime-kuma-ts # SELF-TS
    volumes:
      - ${UPTIME_KUMA_APP_DATA}:/app/data

  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    environment:
      - ALLOW_RESTARTS=1   # DEFAULT=0 | service: portainer,autoheal
      - ALLOW_STOP=0
      - ALLOW_START=0
      - AUTH=0
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1       # DEFAULT=0 | service: portainer,autoheal
      - DISABLE_IPV6=1     # DEFAULT=0
      - DISTRIBUTION=0
      - EVENTS=0           # DEFAULT=1
      - EXEC=0
      - GRPC=0
      - IMAGES=0
      - INFO=0
      - LOG_LEVEL=info
      - NETWORKS=0
      - NODES=0
      - PING=0             # DEFAULT=1
      - PLUGINS=0
      - POST=0
      - SECRETS=0
      - SERVICES=0
      - SESSION=0
      - SOCKET_PATH=/var/run/docker.sock
      - SWARM=0
      - SYSTEM=0
      - TASKS=0
      - VERSION=0          # DEFAULT=1
      - VOLUMES=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    cap_drop: [ALL]
    cap_add:
      - SETGID
    networks:
      - portainer
      - autoheal
      - uptime-kuma
    read_only: true
    tmpfs:
      - /run
