---

services:

  change-detection:
    extends:
      file: ./../common/services.yml
      service: defaults
    image: dgtlmoon/changedetection.io
    networks:
      - change-detection-ts # SELF-TS
    volumes:
      - ${CHANGE_DETECTION_APP_DATA?error}/datastore:/datastore

  fake-data-generator:
    extends:
      file: ./../common/services.yml
      service: lsio # based on base lsio image
    image: ghcr.io/josh1703658784/fake-address-generator-docker:feature-hardcode-selected-states
    networks:
      - fake-data-generator-ts # SELF-TS

  portainer:
    extends:
      file: ./../common/services.yml
      service: defaults
    image: portainer/portainer-ce:2.21.1
    networks:
      - portainer       # SELF
      - portainer-ts    # SELF-TS
    depends_on:
      socket-proxy:     # service:socket-proxy at file bottom
        restart: true
        condition: service_healthy
    volumes:
      - ${PORTAINER_APP_DATA?error}/data:/data

  autoheal:
    extends:
      file: ./../common/services.yml
      service: defaults
    image: willfarrell/autoheal
    networks:
      - autoheal          # SELF
    depends_on:
      socket-proxy:       # service:socket-proxy at file bottom
        restart: true
        condition: service_healthy
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - DOCKER_SOCK=tcp://socket-proxy:2375
      - AUTOHEAL_INTERVAL=5

  kuma:
    extends:
      file: ./../common/services.yml
      service: defaults
    image: louislam/uptime-kuma:1
    networks:
      - kuma      # SELF
      - kuma-ts   # SELF-TS
    volumes:
      - ${UPTIME_KUMA_APP_DATA}:/app/data
    cap_add:
     - CHOWN
     - SETGID
     - SETUID
    depends_on:
      socket-proxy:     # service:socket-proxy at file bottom
        restart: true
        condition: service_healthy

  socket-proxy:
    extends:
      file: ./../common/services.yml
      service: lsio
    image: lscr.io/linuxserver/socket-proxy:latest
    environment:
      - ALLOW_RESTARTS=1   # DEFAULT=0 | service: portainer,autoheal
      - ALLOW_STOP=0
      - ALLOW_START=0
      - AUTH=0
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1       # DEFAULT=0 | service: portainer,autoheal
      - DISABLE_IPV6=1     # DEFAULT=0
      - DISTRIBUTION=0
      - EVENTS=0           # DEFAULT=1
      - EXEC=0
      - GRPC=0
      - IMAGES=0
      - INFO=0
      - LOG_LEVEL=info
      - NETWORKS=0
      - NODES=0
      - PING=0             # DEFAULT=1
      - PLUGINS=0
      - POST=0
      - SECRETS=0
      - SERVICES=0
      - SESSION=0
      - SOCKET_PATH=/var/run/docker.sock
      - SWARM=0
      - SYSTEM=0
      - TASKS=0
      - VERSION=0          # DEFAULT=1
      - VOLUMES=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - portainer
      - autoheal
      - kuma
    healthcheck:
      test: ["CMD", "curl", "--silent", "socket-proxy:2375"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 0s
