---

name: rss

include:
  - path: ./services.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

  - path: ./tailscale.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

  - path: ./configs.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

networks:
  db:
  miniflux-ts:
  redis:
  rsshub-ts:
  rsshub:
  miniflux-db:
  wallabag-redis:
  wallabag-db:
  wallabag-ts:

volumes:
  rsshub-ts:
  miniflux-ts:
  redis-data:
  wallabag-images:
  wallabag-ts:
