---

# @TODO review these https://teddit.net/r/radarr/comments/hbwnb2/a_list_of_all_companion_tools_and_software/
# @TODO https://github.com/TheUltimateC0der/Listrr


name: compose-rss #@TODO remove and recreate all services

include:
  - path: ./services.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets


  - path: ./tailscale.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

  - path: ./configs.yml
    env_file:
      - ./../common/.envrc
      - ./../common/.secrets
      - ./.envrc
      - ./.secrets

networks:
  db:
  miniflux-ts:
  rsshub-ts:
  browserless:
  redis:
  rsshub:
  rsshub-vpn:

volumes:
  miniflux-ts:
  redis-data:
  rsshub-ts:
