configs:

  miniflux-ts:
    content: |
      {
        "TCP": {
          "443": {
            "HTTPS": true
          }
        },
        "Web": {
          "$${TS_CERT_DOMAIN}:443": {
            "Handlers": {
              "/": {
                "Proxy": "http://localhost:${MINIFLUX_PORT?error}"
              }
            }
          }
        }
      }

  rsshub-ts:
    content: |
      {
        "TCP": {
          "443": {
            "HTTPS": true
          }
        },
        "Web": {
          "$${TS_CERT_DOMAIN}:443": {
            "Handlers": {
              "/": {
                "Proxy": "http://rsshub:${RSSHUB_PORT?error}"
              }
            }
          }
        }
      }

  rsshub-vpn-supervisor:
    content: |
      [program:start-script]
      autorestart = false
      startsecs = 0
      user = root
      command = /root/start.sh
      umask = 000

      [program:watchdog-script]
      autorestart = false
      startsecs = 0
      user = nobody
      command = /home/nobody/watchdog.sh
      umask = 000


  wallabag-ts:
    content: |
      {
        "TCP": {
          "443": {
            "HTTPS": true
          }
        },
        "Web": {
          "$${TS_CERT_DOMAIN}:443": {
            "Handlers": {
              "/": {
                "Proxy": "http://wallabag:${WALLABAG_PORT?error}"
              }
            }
          }
        }
      }
